export const Letters = [
  { key: "A", isClicked: false },
  { key: "Z", isClicked: false },
  { key: "E", isClicked: false },
  { key: "R", isClicked: false },
  { key: "T", isClicked: false },
  { key: "Y", isClicked: false },
  { key: "U", isClicked: false },
  { key: "I", isClicked: false },
  { key: "O", isClicked: false },
  { key: "P", isClicked: false },
  { key: "Q", isClicked: false },
  { key: "S", isClicked: false },
  { key: "D", isClicked: false },
  { key: "F", isClicked: false },
  { key: "G", isClicked: false },
  { key: "H", isClicked: false },
  { key: "J", isClicked: false },
  { key: "K", isClicked: false },
  { key: "L", isClicked: false },
  { key: "M", isClicked: false },
  { key: "W", isClicked: false },
  { key: "X", isClicked: false },
  { key: "C", isClicked: false },
  { key: "V", isClicked: false },
  { key: "B", isClicked: false },
  { key: "N", isClicked: false },
];
